spring:
  data:
    rest:
      defaultMediaType: application/json
      default-media-type: application/json
  application:
    name: jukeboxd-api
  jmx:
    enabled: true
  main:
    allow-bean-definition-overriding: true
    banner-mode: log

  flyway:
    enabled: true
    locations: classpath:/db/migration

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:postgresql://localhost:5432/football_db
    username: admin
    password: changeme
    hikari:
      maximum-pool-size: 5
      connection-timeout: 5000
      pool-name: pool-starter
  jpa:
    show-sql: true # TODO: change from true to false
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQLDialect

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: '*'

server:
  port: 8080
  forward-headers-strategy: framework
  servlet:
    context-path: /v1