CREATE SCHEMA IF NOT EXISTS sys;

DROP TABLE IF EXISTS tb_competition;
DROP TABLE IF EXISTS tb_area;
DROP TABLE IF EXISTS tb_person;
DROP TABLE IF EXISTS tb_player;
DROP TABLE IF EXISTS tb_coach;
DROP TABLE IF EXISTS tb_team;

GRANT ALL ON SCHEMA sys to admin;