version: '3.6'
services:
  user_db:
    image: postgres
    container_name: footballql_container
    restart: unless-stopped
    environment:
      POSTGRES_DB: "football_db"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "changeme"
    ports:
      - "5432:5432"
    volumes:
      - postgres-volume:/var/lib/football_db
      - ./custom.cnf:/etc/mysql/conf.d/custom.cnf
volumes:
  postgres-volume: